/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	dispatchuserv1 "github.com/hantaowang/dispatch/pkg/apis/dispatchuser/v1"
	versioned "github.com/hantaowang/dispatch/pkg/client/clientset/versioned"
	internalinterfaces "github.com/hantaowang/dispatch/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/hantaowang/dispatch/pkg/client/listers/dispatchuser/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DispatchUserInformer provides access to a shared informer and lister for
// DispatchUsers.
type DispatchUserInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DispatchUserLister
}

type dispatchUserInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDispatchUserInformer constructs a new informer for DispatchUser type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDispatchUserInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDispatchUserInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDispatchUserInformer constructs a new informer for DispatchUser type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDispatchUserInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetsysV1().DispatchUsers(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetsysV1().DispatchUsers(namespace).Watch(options)
			},
		},
		&dispatchuserv1.DispatchUser{},
		resyncPeriod,
		indexers,
	)
}

func (f *dispatchUserInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDispatchUserInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dispatchUserInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&dispatchuserv1.DispatchUser{}, f.defaultInformer)
}

func (f *dispatchUserInformer) Lister() v1.DispatchUserLister {
	return v1.NewDispatchUserLister(f.Informer().GetIndexer())
}
