/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	netsysio_v1 "github.com/hantaowang/dispatch/pkg/apis/netsysio/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDispatchUsers implements DispatchUserInterface
type FakeDispatchUsers struct {
	Fake *FakeNetsysV1
	ns   string
}

var dispatchusersResource = schema.GroupVersionResource{Group: "netsys.io", Version: "v1", Resource: "dispatchusers"}

var dispatchusersKind = schema.GroupVersionKind{Group: "netsys.io", Version: "v1", Kind: "DispatchUser"}

// Get takes name of the dispatchUser, and returns the corresponding dispatchUser object, and an error if there is any.
func (c *FakeDispatchUsers) Get(name string, options v1.GetOptions) (result *netsysio_v1.DispatchUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dispatchusersResource, c.ns, name), &netsysio_v1.DispatchUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*netsysio_v1.DispatchUser), err
}

// List takes label and field selectors, and returns the list of DispatchUsers that match those selectors.
func (c *FakeDispatchUsers) List(opts v1.ListOptions) (result *netsysio_v1.DispatchUserList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dispatchusersResource, dispatchusersKind, c.ns, opts), &netsysio_v1.DispatchUserList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &netsysio_v1.DispatchUserList{ListMeta: obj.(*netsysio_v1.DispatchUserList).ListMeta}
	for _, item := range obj.(*netsysio_v1.DispatchUserList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dispatchUsers.
func (c *FakeDispatchUsers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dispatchusersResource, c.ns, opts))

}

// Create takes the representation of a dispatchUser and creates it.  Returns the server's representation of the dispatchUser, and an error, if there is any.
func (c *FakeDispatchUsers) Create(dispatchUser *netsysio_v1.DispatchUser) (result *netsysio_v1.DispatchUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dispatchusersResource, c.ns, dispatchUser), &netsysio_v1.DispatchUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*netsysio_v1.DispatchUser), err
}

// Update takes the representation of a dispatchUser and updates it. Returns the server's representation of the dispatchUser, and an error, if there is any.
func (c *FakeDispatchUsers) Update(dispatchUser *netsysio_v1.DispatchUser) (result *netsysio_v1.DispatchUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dispatchusersResource, c.ns, dispatchUser), &netsysio_v1.DispatchUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*netsysio_v1.DispatchUser), err
}

// Delete takes name of the dispatchUser and deletes it. Returns an error if one occurs.
func (c *FakeDispatchUsers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dispatchusersResource, c.ns, name), &netsysio_v1.DispatchUser{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDispatchUsers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dispatchusersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &netsysio_v1.DispatchUserList{})
	return err
}

// Patch applies the patch and returns the patched dispatchUser.
func (c *FakeDispatchUsers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *netsysio_v1.DispatchUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dispatchusersResource, c.ns, name, data, subresources...), &netsysio_v1.DispatchUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*netsysio_v1.DispatchUser), err
}
