/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/hantaowang/dispatch/pkg/apis/ownednamespace/v1"
	scheme "github.com/hantaowang/dispatch/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// OwnedNamespacesGetter has a method to return a OwnedNamespaceInterface.
// A group's client should implement this interface.
type OwnedNamespacesGetter interface {
	OwnedNamespaces(namespace string) OwnedNamespaceInterface
}

// OwnedNamespaceInterface has methods to work with OwnedNamespace resources.
type OwnedNamespaceInterface interface {
	Create(*v1.OwnedNamespace) (*v1.OwnedNamespace, error)
	Update(*v1.OwnedNamespace) (*v1.OwnedNamespace, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.OwnedNamespace, error)
	List(opts metav1.ListOptions) (*v1.OwnedNamespaceList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.OwnedNamespace, err error)
	OwnedNamespaceExpansion
}

// ownedNamespaces implements OwnedNamespaceInterface
type ownedNamespaces struct {
	client rest.Interface
	ns     string
}

// newOwnedNamespaces returns a OwnedNamespaces
func newOwnedNamespaces(c *NetsysV1Client, namespace string) *ownedNamespaces {
	return &ownedNamespaces{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the ownedNamespace, and returns the corresponding ownedNamespace object, and an error if there is any.
func (c *ownedNamespaces) Get(name string, options metav1.GetOptions) (result *v1.OwnedNamespace, err error) {
	result = &v1.OwnedNamespace{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ownednamespaces").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of OwnedNamespaces that match those selectors.
func (c *ownedNamespaces) List(opts metav1.ListOptions) (result *v1.OwnedNamespaceList, err error) {
	result = &v1.OwnedNamespaceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ownednamespaces").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested ownedNamespaces.
func (c *ownedNamespaces) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ownednamespaces").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a ownedNamespace and creates it.  Returns the server's representation of the ownedNamespace, and an error, if there is any.
func (c *ownedNamespaces) Create(ownedNamespace *v1.OwnedNamespace) (result *v1.OwnedNamespace, err error) {
	result = &v1.OwnedNamespace{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ownednamespaces").
		Body(ownedNamespace).
		Do().
		Into(result)
	return
}

// Update takes the representation of a ownedNamespace and updates it. Returns the server's representation of the ownedNamespace, and an error, if there is any.
func (c *ownedNamespaces) Update(ownedNamespace *v1.OwnedNamespace) (result *v1.OwnedNamespace, err error) {
	result = &v1.OwnedNamespace{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ownednamespaces").
		Name(ownedNamespace.Name).
		Body(ownedNamespace).
		Do().
		Into(result)
	return
}

// Delete takes name of the ownedNamespace and deletes it. Returns an error if one occurs.
func (c *ownedNamespaces) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ownednamespaces").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *ownedNamespaces) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ownednamespaces").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched ownedNamespace.
func (c *ownedNamespaces) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.OwnedNamespace, err error) {
	result = &v1.OwnedNamespace{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ownednamespaces").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
