/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/hantaowang/dispatch/pkg/apis/netsysio/v1"
	scheme "github.com/hantaowang/dispatch/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DispatchUsersGetter has a method to return a DispatchUserInterface.
// A group's client should implement this interface.
type DispatchUsersGetter interface {
	DispatchUsers(namespace string) DispatchUserInterface
}

// DispatchUserInterface has methods to work with DispatchUser resources.
type DispatchUserInterface interface {
	Create(*v1.DispatchUser) (*v1.DispatchUser, error)
	Update(*v1.DispatchUser) (*v1.DispatchUser, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.DispatchUser, error)
	List(opts meta_v1.ListOptions) (*v1.DispatchUserList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.DispatchUser, err error)
	DispatchUserExpansion
}

// dispatchUsers implements DispatchUserInterface
type dispatchUsers struct {
	client rest.Interface
	ns     string
}

// newDispatchUsers returns a DispatchUsers
func newDispatchUsers(c *NetsysV1Client, namespace string) *dispatchUsers {
	return &dispatchUsers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dispatchUser, and returns the corresponding dispatchUser object, and an error if there is any.
func (c *dispatchUsers) Get(name string, options meta_v1.GetOptions) (result *v1.DispatchUser, err error) {
	result = &v1.DispatchUser{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dispatchusers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DispatchUsers that match those selectors.
func (c *dispatchUsers) List(opts meta_v1.ListOptions) (result *v1.DispatchUserList, err error) {
	result = &v1.DispatchUserList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dispatchusers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dispatchUsers.
func (c *dispatchUsers) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dispatchusers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a dispatchUser and creates it.  Returns the server's representation of the dispatchUser, and an error, if there is any.
func (c *dispatchUsers) Create(dispatchUser *v1.DispatchUser) (result *v1.DispatchUser, err error) {
	result = &v1.DispatchUser{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dispatchusers").
		Body(dispatchUser).
		Do().
		Into(result)
	return
}

// Update takes the representation of a dispatchUser and updates it. Returns the server's representation of the dispatchUser, and an error, if there is any.
func (c *dispatchUsers) Update(dispatchUser *v1.DispatchUser) (result *v1.DispatchUser, err error) {
	result = &v1.DispatchUser{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dispatchusers").
		Name(dispatchUser.Name).
		Body(dispatchUser).
		Do().
		Into(result)
	return
}

// Delete takes name of the dispatchUser and deletes it. Returns an error if one occurs.
func (c *dispatchUsers) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dispatchusers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dispatchUsers) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dispatchusers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched dispatchUser.
func (c *dispatchUsers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.DispatchUser, err error) {
	result = &v1.DispatchUser{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dispatchusers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
