/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	ownednamespacev1 "github.com/hantaowang/dispatch/pkg/apis/ownednamespace/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOwnedNamespaces implements OwnedNamespaceInterface
type FakeOwnedNamespaces struct {
	Fake *FakeNetsysV1
	ns   string
}

var ownednamespacesResource = schema.GroupVersionResource{Group: "netsys.io", Version: "v1", Resource: "ownednamespaces"}

var ownednamespacesKind = schema.GroupVersionKind{Group: "netsys.io", Version: "v1", Kind: "OwnedNamespace"}

// Get takes name of the ownedNamespace, and returns the corresponding ownedNamespace object, and an error if there is any.
func (c *FakeOwnedNamespaces) Get(name string, options v1.GetOptions) (result *ownednamespacev1.OwnedNamespace, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ownednamespacesResource, c.ns, name), &ownednamespacev1.OwnedNamespace{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ownednamespacev1.OwnedNamespace), err
}

// List takes label and field selectors, and returns the list of OwnedNamespaces that match those selectors.
func (c *FakeOwnedNamespaces) List(opts v1.ListOptions) (result *ownednamespacev1.OwnedNamespaceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ownednamespacesResource, ownednamespacesKind, c.ns, opts), &ownednamespacev1.OwnedNamespaceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &ownednamespacev1.OwnedNamespaceList{ListMeta: obj.(*ownednamespacev1.OwnedNamespaceList).ListMeta}
	for _, item := range obj.(*ownednamespacev1.OwnedNamespaceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ownedNamespaces.
func (c *FakeOwnedNamespaces) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ownednamespacesResource, c.ns, opts))

}

// Create takes the representation of a ownedNamespace and creates it.  Returns the server's representation of the ownedNamespace, and an error, if there is any.
func (c *FakeOwnedNamespaces) Create(ownedNamespace *ownednamespacev1.OwnedNamespace) (result *ownednamespacev1.OwnedNamespace, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ownednamespacesResource, c.ns, ownedNamespace), &ownednamespacev1.OwnedNamespace{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ownednamespacev1.OwnedNamespace), err
}

// Update takes the representation of a ownedNamespace and updates it. Returns the server's representation of the ownedNamespace, and an error, if there is any.
func (c *FakeOwnedNamespaces) Update(ownedNamespace *ownednamespacev1.OwnedNamespace) (result *ownednamespacev1.OwnedNamespace, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ownednamespacesResource, c.ns, ownedNamespace), &ownednamespacev1.OwnedNamespace{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ownednamespacev1.OwnedNamespace), err
}

// Delete takes name of the ownedNamespace and deletes it. Returns an error if one occurs.
func (c *FakeOwnedNamespaces) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(ownednamespacesResource, c.ns, name), &ownednamespacev1.OwnedNamespace{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOwnedNamespaces) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ownednamespacesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &ownednamespacev1.OwnedNamespaceList{})
	return err
}

// Patch applies the patch and returns the patched ownedNamespace.
func (c *FakeOwnedNamespaces) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *ownednamespacev1.OwnedNamespace, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ownednamespacesResource, c.ns, name, data, subresources...), &ownednamespacev1.OwnedNamespace{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ownednamespacev1.OwnedNamespace), err
}
